---
- name: Configure Vagrant .ssh directory.
  file: path=/home/vagrant/.ssh state=directory owner=vagrant group=vagrant mode=0700

- name: Get Vagrant's public key.
  get_url:
    url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    owner: vagrant
    group: vagrant
    mode: 0600
